### ISSUE TITLE
Does not work with ed25519 keys

### ISSUE THREAD

**Issue by Ashaman-** [reynir/qubes-mirage-ssh-agent#16]
Attempts to execute ssh-add with an ed25519 key yield the following output:

Could not add identity "/home/user/.ssh/id_ed25519": communication with agent failed

**Comment by hannesm** [comment]
this is true, FWIW hacl just got ed25519 support in 0.2.0 (see https://github.com/mirage/hacl/pull/35), and awa-ssh supports ed25519 keys as well (in https://github.com/mirage/awa-ssh/pull/16). I don't know anything about the agent protocol and encoding of ed25519 keys. the primitives are there, it should be doable to extend qubes-mirage-ssh-agent with ed25519 support (we should refactor qubes-mirage-ssh-agent and awa-ssh to share code to avoid duplication of encoders and decoders etc.).

**Comment by reynir** [comment]
This should now be working with ssh-agent.0.4.0.
